name: QA (Windows)

on:
  workflow_dispatch:
    inputs:
      portable_tag:
        description: 'which VS portable tag to test'
        default: 'vs-2023H1'
      regexp:
        description: 'which tests to run?'
        default: '.'

jobs:
  QA:
    strategy:
      matrix:
        variant: [ "non-opencl" ]

    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    env:
      REGEXP: ${{ github.event.inputs.regexp }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPO_ORG }}/${{ secrets.REPO_NAME }}
        token: ${{ secrets.REPO_TOKEN }}
        fetch-depth: 0

    - name: Test
      shell: cmd
      run: |
        where OpenCL.dll
        dir C:\Windows\System32\opencl.dll
        del C:\Windows\System32\opencl.dll
        dir C:\Windows\System32\opencl.dll
